version: "2"
services:
  

  db:
    ports:
      - "3306:3306"
    build:
      context: ./mysql
      dockerfile: Dockerfile


  app:
    build: 
     context: ./src
     dockerfile: Dockerfile

    links:
      - db
    ports:
      - "8080:8080"
      - "443:443"
  
